apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: web-dev-namespace
  labels:
    app: my-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: bhanunr/admin-micro:v7
        ports:
        - containerPort: 8080
