apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  namespace: web-dev-namespace
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30004
