name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Scripts
      run: |
        docker build -t maven .
        docker tag maven bhanunr/admin-micro:v7
        docker login -u bhanunr -p dckr_pat_XHyVfeEqySijJLUXT1Vd8BXYmSM 
        docker push bhanunr/admin-micro:v7
